### ISSUE TITLE
[feature request] --defines flag

### ISSUE THREAD

**Issue by E5ten** [ThomasDickey/byacc-snapshots#2]
`--defines=<file>` is a bison extension equivalent to -d but specifying the header file created. The linux kernel makes use of this flag, to get the kernel to build with byacc as YACC instead of bison I had to use this patch:
```
--- scripts/Makefile.lib
+++ scripts/Makefile.lib
@@ -202,7 +202,7 @@
 	$(call if_changed,bison)

 quiet_cmd_bison_h = YACC    $@
-      cmd_bison_h = $(YACC) -o/dev/null --defines=$@ -t -l $<
+      cmd_bison_h = $(YACC) -o/dev/null -d -t -l $< && mv y.tab.h $@

 $(obj)/%.tab.h: $(src)/%.y FORCE
 	$(call if_changed,bison_h)
--- scripts/genksyms/Makefile
+++ scripts/genksyms/Makefile
@@ -15,14 +15,14 @@
 ifeq ($(findstring 1,$(KBUILD_ENABLE_EXTRA_GCC_CHECKS)),)

 quiet_cmd_bison_no_warn = $(quiet_cmd_bison)
-      cmd_bison_no_warn = $(YACC) --version >/dev/null; \
+      cmd_bison_no_warn = $(YACC) -V >/dev/null; \
 			  $(cmd_bison) 2>/dev/null

 $(obj)/parse.tab.c: $(src)/parse.y FORCE
 	$(call if_changed,bison_no_warn)

 quiet_cmd_bison_h_no_warn = $(quiet_cmd_bison_h)
-      cmd_bison_h_no_warn = $(YACC) --version >/dev/null; \
+      cmd_bison_h_no_warn = $(YACC) -V >/dev/null; \
 			    $(cmd_bison_h) 2>/dev/null

 $(obj)/parse.tab.h: $(src)/parse.y FORCE
--- scripts/genksyms/lex.l
+++ scripts/genksyms/lex.l
@@ -30,6 +30,7 @@

 #include "genksyms.h"
 #include "parse.tab.h"
+extern YYSTYPE yylval;

 /* We've got a two-level lexer here.  We let flex do basic tokenization
    and then we categorize those basic tokens in the second stage.  */
```
The last hunk is because without it an error about yylval being undeclared occurs, I don't know much about yacc or lex so I'd think there's probably a more proper fix to that issue, but that in regards to --defines, the replacement I used there is rather hacky, and I doubt it'd get accepted upstream, but if byacc supported --defines there could probably be upstream support for building the kernel with byacc as YACC instead of solely working with bison.

**Comment by ThomasDickey** [comment]
The **`yylval`** detail is interesting, and eliminating the **`mv`** command would be an improvement, but making **_byacc_** use GNU long-options isn't something that that I want to do, because it's unlikely to ever be standardized.

At the moment **_byacc_** is using its own options-parsing, which looks like it could easily use getopt (probably overlooked before since when I began work on it, **_byacc_** was portable to VMS, which lacks that function).

I see that **_bison_** uses **`-D`** for this case (which is the obvious choice for passing a value), so I'll make that change.

**Comment by ThomasDickey** [comment]
I see now why it does not use getopt; will update the manual page.

**Comment by E5ten** [comment]
`--define` or `-D` is a different flag for passing values like you said, `--defines` is for choosing the file that gets output that would normally be `y.tab.h` with `-d`.

**Comment by ThomasDickey** [comment]
done

**Comment by E5ten** [comment]
I understand the reasoning for only using a shortopt, but I think something other than `-D` should be used because bison uses that for the same thing as `--define` which does `-D, --define=NAME[=VALUE]        similar to '%define NAME "VALUE"'` so `-D` used for this would be a conflicting shortopt providing different functionality from the bison one. I think it would be better if a shortopt bison doesn't already use was used, and then I or someone else could possibly ask bison to support said shortopt in place of `--defines`, which would then allow the kernel Makefile to use that shortopt instead of --defines which would make it support bison and byacc.

**Comment by ThomasDickey** [comment]
hmm - I misread the bison manpage (missed the **_"s"_**).  :-(

Sure - suggest a short, non-conflicting option, and I can change it.

**Comment by E5ten** [comment]
I guess `-O` would make sense, because like -o/--output specifies the C file to output `-O` would be like a mirror to `-o` just for definition files.

**Comment by ThomasDickey** [comment]
That, or **_-H_** (either way, there's likely pushback on possible confusion).

**Comment by E5ten** [comment]
Yeah `-H` is definitely a sensible choice as well.

**Comment by ThomasDickey** [comment]
yes... -o versus -O changes the type of file, while -h versus -H changes the purpose.
Neither appears in [bison's source](https://github.com/akimd/bison)

Most of the single-letter options are more than 10 years old (except for -f and -u).
I'll try the -H, since I think it's slightly less confusing.

**Comment by ThomasDickey** [comment]
done

**Comment by E5ten** [comment]
@ThomasDickey Out of curiosity, why doesn't it use getopt?

**Comment by ThomasDickey** [comment]
hmm - I forgot to follow up here, but wrote a note about checking portability of plain "-" (not "--").  I don't see it in [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/functions/getopt.html#tag_16_206).  Originally of course, byacc was written before getopt was standardized.

**Comment by ThomasDickey** [comment]
The issue is that byacc accepts a bare "-" as the filename (for reading from the standard input).

I compared Solaris and Linux, found that a bare **"-"** is treated as a non-option in Solaris (_optind_ points to that token). With Linux, a bare **"-"** is ignored if there are options past that token.  If it happens to be the last token, _optind_ points to **that**.

**Comment by ThomasDickey** [comment]
I had forgotten that GNU getopt can be made to work with this case because it reorders the argv array (moving the nonoption "-" to the end).  See comments in [source-code](https://github.com/gcc-mirror/gcc/blob/master/libiberty/getopt.c).
